version: '3.7'

services:
  # NGINX / PHP
  web:
    image: webwhales/for-wp-nginx:latest
    #image: webwhales/for-wp-nginx:php7.3-fpm
    container_name: web
    hostname: domain.localhost
    volumes:
      - ./templates/site.conf:/etc/nginx/sites-enabled/site.conf
      #- ./templates/site.ini:/usr/local/etc/php/conf.d/wpbasethemedev.ini
      #- ./templates/supervisor-wp.conf:/etc/supervisor/conf.d/supervisor-wp.conf
      #- ./logs/web_nginx:/var/log/nginx
      - ./:/var/www/html
    ports:
      - "80:80"
      - "443:443"