version: '3.7'

services:
  # ==============================================
  # WordPress Containers
  # ==============================================

  # NGINX / PHP
  web:
    image: webwhales/for-wp-nginx:latest
    #image: webwhales/for-wp-nginx:php8.0-fpm
    hostname: domain.localhost
    restart: unless-stopped
    volumes:
      - ./.docker/conf/site.conf:/etc/nginx/sites-enabled/site.conf
      - ./.docker/conf/site.ini:/usr/local/etc/php/conf.d/site.ini
      - ./.docker/conf/supervisor.conf:/etc/supervisor/conf.d/site.conf
      - ./.docker/logs/nginx:/var/log/nginx
      - ./:/var/www/html
    ports:
      - "8080:80"
    links:
      - db

  # MySQL
  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - ./.docker/conf/mysql/docker-entrypoint-initdb.d/create_test_database.sql:/docker-entrypoint-initdb.d/create_test_database.sql
      - db_volume:/var/lib/mysql
      - ./.docker/logs/mysql:/var/log/mysql
    environment:
      # When changing the MYSQL_USER value, don't forget to change it also in the following file:
      #  .docker/conf/mysql/docker-entrypoint-initdb.d/create_test_database.sql
      MYSQL_ROOT_PASSWORD: "x1coJitPx&UI%@cLb7XBtQKN63!ld7wL"
      MYSQL_DATABASE: "wp_db"
      MYSQL_USER: "wp_db_user"
      MYSQL_PASSWORD: "wp_db_pass"
    ports:
      - "3306:3306"

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: domain.localhost
    restart: unless-stopped
    volumes:
      - ./.docker/conf/phpmyadmin-config.php:/etc/phpmyadmin/config.user.inc.php
      - ./.docker/data/phpmyadmin/sessions:/sessions
      - ./.docker/data/phpmyadmin/uploads:/var/uploads
    ports:
      - "8082:80"
    environment:
      PMA_ARBITRARY: "1"
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "x1coJitPx&UI%@cLb7XBtQKN63!ld7wL"
    links:
      - db


# ==============================================
# Volumes
# ==============================================
volumes:
  db_volume: